### ISSUE TITLE
Using docker:dind cannot get from gitlab registry with docker-compose up

### ISSUE THREAD

**Issue by fergyfresh** [tmaier/docker-compose#13]
```
Running with gitlab-runner 11.4.0~beta.754.gad3eebfd (ad3eebfd)
  on docker-auto-scale 72989761
Using Docker executor with image tmaier/docker-compose:latest ...
Starting service docker:dind ...
Pulling docker image docker:dind ...
Using docker image sha256:redacted for docker:dind ...
Waiting for services to be up and running...
Pulling docker image tmaier/docker-compose:latest ...
Using docker image sha256:73454f3a9698ceb448cd79b2ef058607fbd310dce48b7dbb1050d2b00ecc6ea4 for tmaier/docker-compose:latest ...
Running on runner-72989761-project-7091190-concurrent-0 via runner-72989761-srm-1539035673-ce38e01b...
Cloning repository...
Cloning into '/example/redacted'...
Checking out example as redacted...
Skipping Git submodules setup
$ cd docker/compose/
$ docker-compose up
Creating network "compose_default" with the default driver
Pulling example-redacted...
Get https://registry.gitlab.com//example/redacted: denied: access forbidden
ERROR: Job failed: exit code 1
```
I can pull and push docker containers in gitlab ci, but when i use this latest container i cannot push/pull with gitlab's newest runner updates.

**Comment by tmaier** [comment]
Hi,

can you please show me the relevant part of your .gitlab-ci.yml?

This is how the relevant part looks in my case:
```yaml

.docker: &docker
  image: tmaier/docker-compose:latest
  services:
    - docker:dind
  before_script:
    - |
      if [ -z "$DOCKER_HOST" -a "$KUBERNETES_PORT" ]; then
        export DOCKER_HOST='tcp://localhost:2375'
      fi
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - printenv >> .env.test
  variables: &docker_variables
    DOCKER_DRIVER: overlay2
```
