### ISSUE TITLE
dind curl endpoint 

### ISSUE THREAD

**Issue by fergyfresh** [tmaier/docker-compose#14]
Hi. Thanks again for helping me with my last issue.

I have a case where I want to do a quick healthcheck on a `docker-compose up -d` where I can successfully curl the endpoint being created by the compose file.

Here is what the relevant parts of my file look like:
```
compose:
    stage: compose
    image: tmaier/docker-compose:latest
    services:
      - docker:dind
    before_script:
      - apk update
      - apk add -y curl
      - docker info
      - docker-compose --version
      - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    script:
      - cd docker/compose/
      - docker-compose run --use-aliases -d nginx
      - cat /etc/hosts
      - curl --fail http://localhost
```

I have tried all types of things like `http://dockerhost`, `http://docker`, `http://nginx`, `--use-aliases`, `-p 80:80`. The `docker-compose run -d nginx` and `curl --fail http://localhost` works fine on my computer, just doesn't work here, also here is some output that might help you help me.

```
$ cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.3	docker fe41d99555a4 runner-0277ea0f-project-8964623-concurrent-0-docker-0
172.17.0.4	runner-0277ea0f-project-8964623-concurrent-0
$ curl --fail http://localhost
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 80: Connection refused
```
